### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by linukc** [lyclyc52/NeRF_RPN#1]
@lyclyc52 @zymk9 Hi, thank you for the great work. May I ask you when you will approximately release the code?

**Comment by lyclyc52** [comment]
Thank you for your interest. We just released our data and we will try our best to release our code by the end of April.

**Comment by linukc** [comment]
Hi, guys, any updates?

**Comment by shf311709001219** [comment]
Request the code ,thank you .

**Comment by lyclyc52** [comment]
Code has been released.

**Comment by shf311709001219** [comment]
Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月2日(星期二) 中午1:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lyclyc52/NeRF_RPN] Code release (Issue #1)





 
Closed #1 as completed.

**Comment by shf311709001219** [comment]
Thanks

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyclyc52/NeRF_RPN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月1日(星期一) 晚上6:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lyclyc52/NeRF_RPN] Code release (Issue #1)





 
Code has been released.
