### ISSUE TITLE
question about the scannet feature extraction

### ISSUE THREAD

**Issue by MiaApr** [lyclyc52/NeRF_RPN#11]
Hello, thanks for sharing your excellent work!  I am puzzled about the nerf feature extraction for scannet dataset:
I think the viewdir you used here is more likely camera origin positions instead of ray directions,
https://github.com/lyclyc52/NeRF_RPN/blob/2f1d4ce6b2544433fb3e6ce9cf829bac587689cd/data/scannet/run_nerf.py#L1184
In my understanding, the `viewdir` here should be the normalized ray directions, such as
```
bcast_ray_o = poses[i, :3, 3]+ 0.0 * xyz
ray_d = xyz - bcast_ray_o
viewdir /= torch.linalg.norm(ray_d, axis=-1, keepdims=True)
```
Could you please tell me where I got it wrong? Thanks for you help in advance!

**Comment by lyclyc52** [comment]
Thank you for your question.

What you wrote is definitely correct for NeRF rendering. [Line 1184](https://github.com/lyclyc52/NeRF_RPN/blob/2f1d4ce6b2544433fb3e6ce9cf829bac587689cd/data/scannet/run_nerf.py#L118) is just a strategy we select view directions. In the context of the view direction, it should be the view direction of the central point of the image. We just adopt this view direction to all the points in each sampling. Additionally, each column of `poses[i, :3, :3]` is a unit vector so normalization is not necessary.

We didn't conducted ablation study on NeRF Sampling Strategies on ScanNet. It is very likely that [Line 1184](https://github.com/lyclyc52/NeRF_RPN/blob/2f1d4ce6b2544433fb3e6ce9cf829bac587689cd/data/scannet/run_nerf.py#L118) is not a good way to choose view directions.

**Comment by MiaApr** [comment]
Thanks for your reply!
