### ISSUE TITLE
The number of scenes in the NeRF and RPN dataset does not match.

### ISSUE THREAD

**Issue by jk45698** [lyclyc52/NeRF_RPN#13]
**The number of scenes** in the NeRF dataset and RPN dataset provided in OneDrive for **Hypersim** does not match. The hypersim_nerf_data dataset contains 250 scenes, while the hypersim_rpn_data dataset contains 303 scenes.

**Comment by zymk9** [comment]
Hi. The number of scenes under `hypersim_nerf_data` is correct (250 scenes). The extra data in `hypersim_rpn_data` are from some of the scenes we excluded in our final dataset as they have poor NeRF quality and/or bad annotations. However we forgot to remove them when releasing the dataset. Sorry for the confusion.
