### ISSUE TITLE
How to visualize bounding boxes in instant-ngp

### ISSUE THREAD

**Issue by rahulswa08** [lyclyc52/NeRF_RPN#16]
Hi,

 I can visualize the NeRF but cannot visualize bounding boxes using NeRF. I have generated json files from proposal2ngp.py file. But still I couldn't visualize bounding boxes. Am I doing anything wrong?

**Comment by lyclyc52** [comment]
proposal2ngp.py is used to align the bounding boxes with the ngp coordinate. You cannot directly see the bounding boxes in NeRF.  To visualize them, you can project bounding boxes to 2D images and modify the nerf output images.

**Comment by rahulswa08** [comment]
Thanks for your response, Is there any script available to do that?

**Comment by lyclyc52** [comment]
As we mentioned in [README](https://github.com/lyclyc52/NeRF_RPN/tree/main/data) of our dataset, you can refer to [this](../nerf_rpn/scripts/visualize_rpn_input.py).

**Comment by rahulswa08** [comment]
Oh okay. So I have checked the instant ngp fork repository. I have a transforms.json which has bounding boxes (as mentioned [here](https://github.com/zymk9/instant-ngp/tree/master/scripts#bounding-box-visualization). 

 So, if I run `./build/testbed --scene data/front3d/scene_04/transforms_train.json` this command. 

Will I be able to visualize NeRF rendering and bounding boxes ovelaped in instant-ngp?

**Comment by lyclyc52** [comment]
We use the Python scripts modified from the original instant ngp repo. You can check `run.py` and `render_bbox.py`.

**Comment by rahulswa08** [comment]
thanks @lyclyc52 , 
I  am able to render the output with boxes now...but I observe lot of extra boxes along with ground truth boxes...is this expected behavior?  I have attached screenshot..
![image](https://github.com/lyclyc52/NeRF_RPN/assets/114314631/96920c56-5220-4954-8d9a-a20d326f4bee)

**Comment by rahulswa08** [comment]
ohh okay...sounds good...that clarifies...closing the issue...thanks again for your prompt replies.
