### ISSUE TITLE
How to generate bounding boxes in obb folder for front3d dataset

### ISSUE THREAD

**Issue by zubair-irshad** [lyclyc52/NeRF_RPN#17]
Hi authors, 

Great work! Is there a script I can use to generate bounding box npy files for front3d dataset that takes in bounding_boxes from `transforms.json` file and nerf feature grid and outputs npy files for front3d scenes? I am trying to use a script similar to hypersim but I get errors specifically I get visualizations which looks strange.. Any help would be much appreciated, thanks! 
![image](https://github.com/lyclyc52/NeRF_RPN/assets/32943733/21f3d724-3eeb-41d4-be0b-4200c74c9f67)

**Comment by zubair-irshad** [comment]
when I plot the bounding_boxes in the obb folder you provide, they look well aligned. Can you please share your process_boxes.py script for front3d dataset? Thank you!

![image](https://github.com/lyclyc52/NeRF_RPN/assets/32943733/797433bd-f207-401d-addf-031462df83c5)

**Comment by lyclyc52** [comment]
We used the similar code of Hypersim on 3dfront to convert nerf bbox to grid, except that we do not permute yz axis for 3dfront, because z axis already points up. I'm sorry we don't keep a seperate version of that code for 3dfront. 

Also, we predict the room bounding box using object boxes in Hypersim, while the 3dfront room bboxes are provided so you can directly use them.

**Comment by lyclyc52** [comment]
One way to check whether it is aligned is to calculate the ratio of the scene bounding box to the feature resolution. If it is aligned, the ratios of the three sides should be very close.

**Comment by DifuTan** [comment]
How can I get such a visual result? I would be very grateful if you could tell me.

> Hi authors,
> 
> Great work! Is there a script I can use to generate bounding box npy files for front3d dataset that takes in bounding_boxes from `transforms.json` file and nerf feature grid and outputs npy files for front3d scenes? I am trying to use a script similar to hypersim but I get errors specifically I get visualizations which looks strange.. Any help would be much appreciated, thanks! ![image](https://private-user-images.githubusercontent.com/32943733/270512297-21f3d724-3eeb-41d4-be0b-4200c74c9f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNTkzNTgsIm5iZiI6MTcwMTI1OTA1OCwicGF0aCI6Ii8zMjk0MzczMy8yNzA1MTIyOTctMjFmM2Q3MjQtM2VlYi00MWQ0LWJlMGItNDIwMGM3NGM5ZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDExNTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MDJlNGQzYWRlMjRiOWRiZmY4YjYyZmI0MTFiMzA3Nzg4OTg4YzQ5NmU1YTMzMGI1YjY3YWNhMjkxMjYxMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rCUyXrVIigeslD2c0_R4f7ttioMYPPm9Mwy66a6hKqw)

**Comment by DifuTan** [comment]
Hello！
How can I get such a visualization? I would be very grateful if you could tell me.

> Hi authors,
> 
> Great work! Is there a script I can use to generate bounding box npy files for front3d dataset that takes in bounding_boxes from `transforms.json` file and nerf feature grid and outputs npy files for front3d scenes? I am trying to use a script similar to hypersim but I get errors specifically I get visualizations which looks strange.. Any help would be much appreciated, thanks! ![image](https://private-user-images.githubusercontent.com/32943733/270512297-21f3d724-3eeb-41d4-be0b-4200c74c9f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNTk3MTQsIm5iZiI6MTcwMTI1OTQxNCwicGF0aCI6Ii8zMjk0MzczMy8yNzA1MTIyOTctMjFmM2Q3MjQtM2VlYi00MWQ0LWJlMGItNDIwMGM3NGM5ZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEyMDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYTcyODE4NjRlMDMxZmYxNjQ4NTAwMTY0ZGU1ODk4OTE3OTk1YmY0NzQxZjVhMjg1NTAxZWFkOTc4ZDQ1YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WqYjuZ7jBzlWhfuVF6kwuMNc11JievygLPatEs5aTpw)

**Comment by lyclyc52** [comment]
You can refer to the code [here](../tree/main/nerf_rpn/scripts).

**Comment by DifuTan** [comment]
Thank you very much!
