### ISSUE TITLE
obb in dataset

### ISSUE THREAD

**Issue by adajdioadhwoadh** [lyclyc52/NeRF_RPN#27]
When i use obboxes, the last dim of the tensor is always 6 not 7.So this bug occurs: RuntimeError:start(6)+length(1) exceeds dimension size(6). The code is "center, w, l, h, theta = torch.split(obboxes, [3, 1, 1, 1, 1], dim=-1)", obboxes.shape = (244, 6), but the last dim should be 7.

**Comment by zymk9** [comment]
That seems a bit odd. The last dim for OBB input is indeed supposed to be 7 instead of 6. Could you please check if the correct OBB input is loaded?

**Comment by adajdioadhwoadh** [comment]
But I use the OBB offered in this website, could you please give me a new link?

**Comment by at82** [comment]
I'm having the same issue with hypersim data. Did you solve this issue?

**Comment by adajdioadhwoadh** [comment]
> I'm having the same issue with hypersim data. Did you solve this issue?
Not at all

**Comment by adajdioadhwoadh** [comment]
> I'm having the same issue with hypersim data. Did you solve this issue?

Can run the code normally on 3D-FRONT dataset?

**Comment by at82** [comment]
> > I'm having the same issue with hypersim data. Did you solve this issue?
> 
> Can run the code normally on 3D-FRONT dataset?

No, I cannot run it on 3D-Front dataset. I get the same error.

**Comment by adajdioadhwoadh** [comment]
This issue have been closed
