### ISSUE TITLE
why obboxes dim-1 is 6 not 7?

### ISSUE THREAD

**Issue by adajdioadhwoadh** [lyclyc52/NeRF_RPN#28]
The code"center, w, l, h, theta = torch.split(obboxes, [3, 1, 1, 1, 1], dim=-1)" in nerfrpn/model/coder/misc.py  is wrong
The bug is RuntimeError: start (6) + length (1) exceeds dimension size (6).
And I check the obboxes, its shape is (183, 6)
But the last dim of obb isn't 7?And I check the .npy file in obb, it's 7.

**Comment by at82** [comment]
Did you solve this issue?

**Comment by lyclyc52** [comment]
It seems that the output dimension of the network is wrong. If the rotated_bbox is True, the last dimension of the output of RPNHead should be 7. Please double check.

**Comment by at82** [comment]
> It seems that the output dimension of the network is wrong. If the rotated_bbox is True, the last dimension of the output of RPNHead should be 7. Please double check.

How do I solve the issue then?

**Comment by lyclyc52** [comment]
It sounds a bit odd. Did you add the flag `--rotated_bbox`? If so, what is the architecture of the RPNHead?

**Comment by adajdioadhwoadh** [comment]
> It sounds a bit odd. Did you add the flag `--rotated_bbox`? If so, what is the architecture of the RPNHead? Please provide more information about how you run the code.
I have solved this issue follow your advice, thank you very much!
